web:
  build: .
  working_dir: /allura
  command: paster serve Allura/docker-dev.ini --reload
  ports:
    - "8080:8080"
  volumes:
    - .:/allura

    # mounting it separatelly to create git, svn, hg directories automatically
    - /allura-data/scm/git:/allura-data/scm/git
    - /allura-data/scm/hg:/allura-data/scm/hg
    - /allura-data/scm/svn:/allura-data/scm/svn
  links:
    - mongo
mongo:
  image: mongo:2.6
  expose:
    - "27017"
  volumes:
    - /allura-data/mongo:/data/db
