web:
  build: .
  working_dir: /allura
  command: bash -c 'cd Allura && paster serve docker-dev.ini --reload'
  ports:
    - "8080:8080"
  volumes:
    - .:/allura
    # mount env to allow update and sharing with taskd container
    - env-docker/python:/usr/local/lib/python2.7
    - env-docker/bin:/usr/local/bin
    # mounting it separatelly to create git, svn, hg directories automatically
    - /allura-data/scm/git:/allura-data/scm/git
    - /allura-data/scm/hg:/allura-data/scm/hg
    - /allura-data/scm/svn:/allura-data/scm/svn
  links:
    - mongo
    - solr

taskd:
  image: allura_web
  working_dir: /allura/Allura
  command: paster taskd docker-dev.ini
  volumes_from:
    - web
  links:
    - mongo
    - solr

solr:
  build: solr_config
  working_dir: /solr/solr-4.2.1/example
  command: java -jar start.jar
  ports:
    - "8983:8983"
  volumes:
    - /allura-data/solr:/solr/solr-4.2.1/example/solr/collection1/data

mongo:
  image: mongo:2.6
  expose:
    - "27017"
  volumes:
    - /allura-data/mongo:/data/db
